### PR TITLE
Add jsonpath to Predicate

### PR DESCRIPTION
**Pull request by yevhen-m**

### CODE REVIEW

**Comment by brunns** [comment]
Looks like there's come test coverage missing.

**Comment by yevhen-m** [comment]
Any estimate on releasing this change?

**Comment by brunns** [comment]
I just need to fix the build - should be soonish.

**Comment by yevhen-m** [comment]
Thanks, would be great, I need this change to proceed.

**Comment by brunns** [comment]
https://pypi.org/project/mbtest/#history released.

**Pull request merged**
