### PR TITLE
Additional functions to server

### PR DESCRIPTION
**Pull request by jbackman**
https://github.com/brunns/mbtest/issues/54

### CODE REVIEW

**Comment by brunns** [comment]
Happy to merge this once it's rebasable.

**Comment by brunns** [comment]
I see this:

Screenshot 2021-06-29 at 15 13 08

**Comment by jbackman** [comment]
I see this - strange!:

image

**Comment by brunns** [comment]
Ah - I can merge it, but not rebase it. Probably something to do with the fact that it includes commits from #58 for some reason.

**Pull request merged**
