### PR TITLE
Backport separate out classes.

### PR DESCRIPTION
**Pull request by colinschoen**
Backports 66b130a70c293797e1f01eeddf4b73ccb678baa7

### CODE REVIEW

**Comment by colinschoen** [comment]
I'll fix the formatting here in a moment.

**Comment by brunns** [comment]
We'd want to remove the original `imposters.py` as well I think.

Also we should probably retain the `__future__` imports in the 2.7 branch?

**Comment by colinschoen** [comment]
Whoops. Done.

**Comment by colinschoen** [comment]
Remaining CI failures are not new.

**Comment by brunns** [comment]
Looks good to me. The build failed because the Codacy token isn't set - I'll look at silencing that.

**Pull request merged**
