### PR TITLE
Backport add http `HEAD` method

### PR DESCRIPTION
**Pull request by colinschoen**

### CODE REVIEW

**Comment by colinschoen** [comment]
@brunns Would you be willing to cut a new version for the backports 1.x line? The missing `HEAD` method is blocking a use case for me.

**Comment by brunns** [comment]
Sure, no problem. Over the weekend OK?

Cheers,
Simon B.
@brunns
07963 351009

**Comment by colinschoen** [comment]
Of course. Thanks so much!

**Comment by brunns** [comment]
Released 1.5.0. :-)

**Comment by colinschoen** [comment]
You rock! Thanks

**Pull request merged**
