### PR TITLE
added not operator

### PR DESCRIPTION
**Pull request by SShatun**

### CODE REVIEW

**Comment by brunns** [comment]
Does this work by itself? I think we need a `NotPredicate`, analogous to the `AndPredicate` and `OrPredicate`, don't we?

**Comment by brunns** [comment]
Using it could something like:

```python

def test_not_predicate(mock_server):
    imposter = Imposter(Stub(~Predicate(query={"foo": "bar"}), Response(body="black pudding")))

    with mock_server(imposter) as s:
        logger.debug("server: %s", s)

        r1 = requests.get(f"{imposter.url}/", params={"foo": "baz"})
        r2 = requests.get(f"{imposter.url}/", params={"foo": "bar"})

        assert_that(r1, is_response().with_body("black pudding"))
        assert_that(r2, not_(is_response().with_body("black pudding")))
```

**Comment by brunns** [comment]
Does https://github.com/brunns/mbtest/commit/e59b7d5cb5f013d0a37a9a0a90d26dda08503364 look any good?

**Comment by SShatun** [comment]
Hi! Excuse me for disappearing.
There actually problems with parsing "not", "or", "and" predicates:

```
 @classmethod
    def from_structure(cls, structure: JsonStructure) -> "Predicate":
        operators = tuple(filter(Predicate.Operator.has_value, structure.keys()))
        if len(operators) != 1:
>           raise Predicate.InvalidPredicateOperator(
                "Each predicate must define exactly one operator."
            )
E           mbtest.imposters.predicates.Predicate.InvalidPredicateOperator: Each predicate must define exactly one operator. 

```
Mock predicates looks this like:

```
"predicates": [
    {
      "and": [
        {
          "matches": {
            "body": "OrderStatusReport",
            "headers": {
              "x-aer-test-id": "bec10cf1-e3cf-4bb1-ac03-1252becc16f4"
            }
          },
          "caseSensitive": false
        },
        {
          "matches": {
            "body": "\"doctype\":3",
            "headers": {
              "x-aer-test-id": "bec10cf1-e3cf-4bb1-ac03-1252becc16f4"
            }
          },
          "caseSensitive": false
        }
      ]
    }
  ]
```
  
  I think problems with `from_structure` method of `Predicate`
  Maybe there must be usage of BasePredicate.from_structure?
  @brunns

**Comment by SShatun** [comment]
https://github.com/brunns/mbtest/pull/42/commits/d3618878125e4d767cceda8bca6ce4ce290324b9#diff-517708e1d223826429b7e5dc98ba502439916afd0e0f53f103671dc1550e76b5R48
I think this should help

**Comment by brunns** [comment]
Thanks for this. I'm having trouble recreating this defect as a unit test, though. This is what I have:


```python
def test_and_predicate_structure_roundtrip_for_pr_42():
    expected = Predicate(
        body="OrderStatusReport",
        headers={"x-aer-test-id": "bec10cf1-e3cf-4bb1-ac03-1252becc16f4"},
        operator=Predicate.Operator.MATCHES,
        case_sensitive=False,
    ) & Predicate(
        body='"doctype":3',
        headers={"x-aer-test-id": "bec10cf1-e3cf-4bb1-ac03-1252becc16f4"},
        operator=Predicate.Operator.MATCHES,
        case_sensitive=False,
    )

    structure = json.loads(
        """{
      "and": [
        {
          "matches": {
            "body": "OrderStatusReport",
            "headers": {
              "x-aer-test-id": "bec10cf1-e3cf-4bb1-ac03-1252becc16f4"
            }
          },
          "caseSensitive": false
        },
        {
          "matches": {
            "body": "\\"doctype\\":3",
            "headers": {
              "x-aer-test-id": "bec10cf1-e3cf-4bb1-ac03-1252becc16f4"
            }
          },
          "caseSensitive": false
        }
      ]
    }"""
    )

    # When
    actual = BasePredicate.from_structure(structure)

    # Then
    assert_that(actual, instance_of(AndPredicate))
    assert_that(actual, has_identical_properties_to(expected))
```

But it's passing fine, without your PR merged. What am I missing?

**Comment by brunns** [comment]
Oh, wait - I see it now:

```python
def test_imposter_structure_roundtrip_for_pr_42():
    # Given
    expected = Imposter(Stub(Predicate(path="a") & Predicate(path="b")))
    structure = expected.as_structure()

    # When
    actual = Imposter.from_structure(structure)

    # Then
    assert_that(actual, instance_of(Imposter))
    assert_that(actual, has_identical_properties_to(expected, ignoring="configuration_url"))
```

**Comment by brunns** [comment]
Great catch, thanks. Do you want to go ahead an add a test like this to `tests/unit/mbtest/test_imposter.py`, and I'll merge it in.

**Comment by SShatun** [comment]
Made one parametrized tests. What do you think?

**Comment by SShatun** [comment]
Weird. What's wrong with tests

**Comment by brunns** [comment]
There's a flaky test there. I need to fix that! All OK on a rerun.

**Comment by brunns** [comment]
Looks fantastic, thanks.

**Comment by SShatun** [comment]
Thank you!

**Comment by brunns** [comment]
2.5.2 released.

**Pull request merged**
